"""added agent tables

Revision ID: a2a811933868
Revises: d7cf74f91a52
Create Date: 2026-03-15 19:38:26.090675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2a811933868'
down_revision: Union[str, Sequence[str], None] = 'd7cf74f91a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='account')
    op.alter_column('agents', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='agents')
    op.drop_constraint(op.f('fk_agents_being'), 'agents', schema='agents', type_='foreignkey')
    op.create_foreign_key(None, 'agents', 'beings', ['being_id'], ['id'], source_schema='agents', referent_schema='identity')
    op.alter_column('task_executions', 'result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='agents')
    op.create_index('idx_task_queue_priority', 'task_queue', ['priority'], unique=False, schema='agents')
    op.create_index('idx_tasks_status', 'tasks', ['status_id'], unique=False, schema='agents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_status', table_name='tasks', schema='agents')
    op.drop_index('idx_task_queue_priority', table_name='task_queue', schema='agents')
    op.alter_column('task_executions', 'result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='agents')
    op.drop_constraint(None, 'agents', schema='agents', type_='foreignkey')
    op.create_foreign_key(op.f('fk_agents_being'), 'agents', 'beings', ['being_id'], ['id'], source_schema='agents', referent_schema='identity', ondelete='CASCADE')
    op.alter_column('agents', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='agents')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'),
               schema='account')
    # ### end Alembic commands ###
