"""add scheduler system

Revision ID: b1a83cc8f4ed
Revises: da3d6b5a26fa
Create Date: 2026-03-23 21:03:49.518772

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1a83cc8f4ed"
down_revision: Union[str, Sequence[str], None] = "da3d6b5a26fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS automation")

    op.create_table(
        "scheduled_task_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SUCCESS", "FAILED", name="execution_status_enum"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="automation",
    )
    op.create_table(
        "scheduled_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "schedule_type",
            sa.Enum("INTERVAL", "CRON", "ONCE", name="schedule_type_enum"),
            nullable=False,
        ),
        sa.Column("cron_expression", sa.Text(), nullable=True),
        sa.Column("interval_seconds", sa.Integer(), nullable=True),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "PAUSED", "COMPLETED", name="task_status_enum"),
            nullable=False,
        ),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="automation",
    )
    op.create_foreign_key(
        "fk_task_exec_task_id",
        "scheduled_task_executions",
        "scheduled_tasks",
        ["task_id"],
        ["id"],
        source_schema="automation",
        referent_schema="automation",
        ondelete="CASCADE",
    )

    op.create_index(
        "idx_task_exec_task_id",
        "scheduled_task_executions",
        ["task_id"],
        schema="automation",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_task_exec_task_id",
        table_name="scheduled_task_executions",
        schema="automation",
    )

    op.drop_constraint(
        "fk_task_exec_task_id",
        "scheduled_task_executions",
        schema="automation",
        type_="foreignkey",
    )

    op.drop_table("scheduled_task_executions", schema="automation")
    op.drop_table("scheduled_tasks", schema="automation")

    sa.Enum(name="execution_status_enum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="schedule_type_enum").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="task_status_enum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
