"""initial schema

Revision ID: da3d6b5a26fa
Revises:
Create Date: 2026-03-18 16:42:24.389257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "da3d6b5a26fa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS identity")
    op.execute("CREATE SCHEMA IF NOT EXISTS account")
    op.execute("CREATE SCHEMA IF NOT EXISTS agents")

    op.create_table(
        "preference_types",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("data_type", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        schema="account",
    )
    op.create_table(
        "autonomy_levels",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("level", sa.SmallInteger(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="agents",
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="agents",
    )
    op.create_table(
        "models",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="agents",
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="agents",
    )
    op.create_table(
        "task_statuses",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="agents",
    )
    op.create_table(
        "team_roles",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="agents",
    )
    op.create_table(
        "being_roles",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="identity",
    )
    op.create_table(
        "being_types",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="identity",
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("department_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"], ["agents.departments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("department_id", "name", name="uq_department_team"),
        schema="agents",
    )
    op.create_index(
        "idx_teams_department",
        "teams",
        ["department_id"],
        unique=False,
        schema="agents",
    )
    op.create_table(
        "beings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("being_type_id", sa.SmallInteger(), nullable=False),
        sa.Column("being_role_id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["being_role_id"],
            ["identity.being_roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["being_type_id"],
            ["identity.being_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="identity",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("being_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["being_id"],
            ["identity.beings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
        schema="account",
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("being_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("model_id", sa.SmallInteger(), nullable=False),
        sa.Column("autonomy_level_id", sa.SmallInteger(), nullable=False),
        sa.Column("role_id", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["autonomy_level_id"],
            ["agents.autonomy_levels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["being_id"],
            ["identity.beings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["agents.models.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["agents.roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("being_id"),
        schema="agents",
    )
    op.create_table(
        "password_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("algorithm", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["account.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="account",
    )
    op.create_index(
        "idx_password_credentials_user",
        "password_credentials",
        ["user_id"],
        unique=False,
        schema="account",
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["account.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="account",
    )
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("preference_type_id", sa.SmallInteger(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["preference_type_id"],
            ["account.preference_types.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["account.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "preference_type_id"),
        schema="account",
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_agent_id", sa.UUID(), nullable=True),
        sa.Column("assigned_agent_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("status_id", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_agent_id"],
            ["agents.agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_agent_id"],
            ["agents.agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["agents.task_statuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="agents",
    )
    op.create_index(
        "idx_tasks_status", "tasks", ["status_id"], unique=False, schema="agents"
    )
    op.create_table(
        "team_members",
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("team_role_id", sa.SmallInteger(), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.agents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["agents.teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["team_role_id"],
            ["agents.team_roles.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "agent_id"),
        schema="agents",
    )
    op.create_index(
        "idx_team_members_agent",
        "team_members",
        ["agent_id"],
        unique=False,
        schema="agents",
    )
    op.create_table(
        "task_executions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("status_id", sa.SmallInteger(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["agents.task_statuses.id"],
        ),
        sa.ForeignKeyConstraint(["task_id"], ["agents.tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="agents",
    )
    op.create_index(
        "idx_task_executions_task",
        "task_executions",
        ["task_id"],
        unique=False,
        schema="agents",
    )
    op.create_table(
        "task_queue",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column(
            "queued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["agents.tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
        schema="agents",
    )
    op.create_index(
        "idx_task_queue_priority",
        "task_queue",
        ["priority"],
        unique=False,
        schema="agents",
    )
    op.create_table(
        "task_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("execution_id", sa.UUID(), nullable=False),
        sa.Column("log_level", sa.Text(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["agents.task_executions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="agents",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_logs", schema="agents")
    op.drop_index("idx_task_queue_priority", table_name="task_queue", schema="agents")
    op.drop_table("task_queue", schema="agents")
    op.drop_index(
        "idx_task_executions_task", table_name="task_executions", schema="agents"
    )
    op.drop_table("task_executions", schema="agents")
    op.drop_index("idx_team_members_agent", table_name="team_members", schema="agents")
    op.drop_table("team_members", schema="agents")
    op.drop_index("idx_tasks_status", table_name="tasks", schema="agents")
    op.drop_table("tasks", schema="agents")
    op.drop_table("user_preferences", schema="account")
    op.drop_table("sessions", schema="account")
    op.drop_index(
        "idx_password_credentials_user",
        table_name="password_credentials",
        schema="account",
    )
    op.drop_table("password_credentials", schema="account")
    op.drop_table("agents", schema="agents")
    op.drop_table("users", schema="account")
    op.drop_table("beings", schema="identity")
    op.drop_index("idx_teams_department", table_name="teams", schema="agents")
    op.drop_table("teams", schema="agents")
    op.drop_table("being_types", schema="identity")
    op.drop_table("being_roles", schema="identity")
    op.drop_table("team_roles", schema="agents")
    op.drop_table("task_statuses", schema="agents")
    op.drop_table("roles", schema="agents")
    op.drop_table("models", schema="agents")
    op.drop_table("departments", schema="agents")
    op.drop_table("autonomy_levels", schema="agents")
    op.drop_table("preference_types", schema="account")
    # ### end Alembic commands ###
